formatter: "markdown" # this is required

version: ">= 0.13.0"

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  {{ .Requirements }}

  {{ .Resources }}

  ## Module Usage
  More usage examples available in .\examples\ folder
  ### Simple Example
  ```hcl
  {{ include "examples/simple/main.tf" }}
  ```
  ### Intermediate Example
  ```hcl
  {{ include "examples/intermediate/main.tf" }}
  ```
  ### Advanced Example
  ```hcl
  {{ include "examples/advanced/main.tf" }}
  ```

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: false
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true